config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, :optional => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :address

  accepts_nested_attributes_for :address
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:ziptwo, :citytwo, :statetwo, :boroughtwo, :streettwo, :numbertwo, :comptwo, :typetwo, :customer_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.build_address
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :cpf, :phone, :email, :zip, :city, :state, :borough, :street, :number, :comp, :type, :address_attributes => [:ziptwo, :citytwo, :statetwo, :boroughtwo, :streettwo, :numbertwo, :comptwo, :typetwo] )
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/addresses/_form.html.erb
<%= form_for(address) do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ziptwo %>
    <%= f.text_field :ziptwo %>
  </div>

  <div class="field">
    <%= f.label :citytwo %>
    <%= f.text_field :citytwo %>
  </div>

  <div class="field">
    <%= f.label :statetwo %>
    <%= f.text_field :statetwo %>
  </div>

  <div class="field">
    <%= f.label :boroughtwo %>
    <%= f.text_field :boroughtwo %>
  </div>

  <div class="field">
    <%= f.label :streettwo %>
    <%= f.text_field :streettwo %>
  </div>

  <div class="field">
    <%= f.label :numbertwo %>
    <%= f.text_field :numbertwo %>
  </div>

  <div class="field">
    <%= f.label :comptwo %>
    <%= f.text_field :comptwo %>
  </div>

  <div class="field">
    <%= f.label :typetwo %>
    <%= f.text_field :typetwo %>
  </div>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Ziptwo</th>
      <th>Citytwo</th>
      <th>Statetwo</th>
      <th>Boroughtwo</th>
      <th>Streettwo</th>
      <th>Numbertwo</th>
      <th>Comptwo</th>
      <th>Typetwo</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.ziptwo %></td>
        <td><%= address.citytwo %></td>
        <td><%= address.statetwo %></td>
        <td><%= address.boroughtwo %></td>
        <td><%= address.streettwo %></td>
        <td><%= address.numbertwo %></td>
        <td><%= address.comptwo %></td>
        <td><%= address.typetwo %></td>
        <td><%= address.customer %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ziptwo:</strong>
  <%= @address.ziptwo %>
</p>

<p>
  <strong>Citytwo:</strong>
  <%= @address.citytwo %>
</p>

<p>
  <strong>Statetwo:</strong>
  <%= @address.statetwo %>
</p>

<p>
  <strong>Boroughtwo:</strong>
  <%= @address.boroughtwo %>
</p>

<p>
  <strong>Streettwo:</strong>
  <%= @address.streettwo %>
</p>

<p>
  <strong>Numbertwo:</strong>
  <%= @address.numbertwo %>
</p>

<p>
  <strong>Comptwo:</strong>
  <%= @address.comptwo %>
</p>

<p>
  <strong>Typetwo:</strong>
  <%= @address.typetwo %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @address.customer %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nome do Cliente' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="field">
    <%= f.label :phone, 'Telefone' %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
<strong>Endereço Principal:</strong>
  <div class="field">
    <%= f.label :zip, 'Cep' %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :city, 'Cidade' %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state, 'Estado' %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :borough, 'Bairro' %>
    <%= f.text_field :borough %>
  </div>

  <div class="field">
    <%= f.label :street, 'Rua' %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :number, 'Número' %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :comp, 'Complemento' %>
    <%= f.text_field :comp %>
  </div>

  <div class="field">
    <%= f.label :type, 'Tipo' %>
    <%= f.text_field :type %>
  </div>

  <Strong>Favor Adicionar os endereços secundários</Strong>

  <table>
    <tbody>
    <%= f.fields_for :address do |ff|%>
      <th class="field">
        <%= ff.label :ziptwo, 'Cep' %>
        <%= ff.text_field :ziptwo %>
      </th>

      <th class="field">
        <%= ff.label :citytwo, 'Cidade' %>
        <%= ff.text_field :citytwo %>
      </th>

      <th class="field">
        <%= ff.label :statetwo, 'Estado' %>
        <%= ff.text_field :statetwo %>
      </th>

      <th class="field">
        <%= ff.label :boroughtwo, 'Bairro' %>
        <%= ff.text_field :boroughtwo %>
      </th>

      <th class="field">
        <%= ff.label :streettwo, 'Rua' %>
        <%= ff.text_field :streettwo %>
      </th>

      <th class="field">
        <%= ff.label :numbertwo, 'Número' %>
        <%= ff.text_field :numbertwo %>
      </th>

      <th class="field">
        <%= ff.label :comptwo, 'Complemento' %>
        <%= ff.text_field :comptwo %>
      </th>
    <%end %>
    </tbody>
  </table>


  <div class="actions">
    <%= f.submit 'Criar Cliente' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Zip</th>
      <th>City</th>
      <th>State</th>
      <th>Borough</th>
      <th>Street</th>
      <th>Number</th>
      <th>Comp</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.cpf %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= customer.zip %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state %></td>
        <td><%= customer.borough %></td>
        <td><%= customer.street %></td>
        <td><%= customer.number %></td>
        <td><%= customer.comp %></td>
        <td><%= customer.type %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @customer.cpf %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @customer.zip %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state %>
</p>

<p>
  <strong>Borough:</strong>
  <%= @customer.borough %>
</p>

<p>
  <strong>Street:</strong>
  <%= @customer.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @customer.number %>
</p>

<p>
  <strong>Comp:</strong>
  <%= @customer.comp %>
</p>

<p>
  <strong>Type:</strong>
  <%= @customer.type %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XSolar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>